version : "2"

services:
  hybridcloud:
    build: .
#    image: hybridcloud
    container_name: hybridcloud
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime
    - /apps/hybridcloud/openrc:/openrc
    - /apps/hybridcloud/heat_templates:/heat_templates/
