heat_template_version: rocky
description:  MariaDB
parameters:
  image:
    type: string
    description: image use for MariaDB
    default: Debian 11.2 bullseye
  flavor:
    type: string
    description: flavor used by MariaDB
    default: a1-ram2-disk20-perf1
  network:
    type: string
    description: network used by MariaDB
    default: MariaDB-network
  subnet_id:
    type: string
    description: dedicated subnet for MariaDB
    default: MariaDB-subnet
  floating_network_id:
    type: string
    description: UUID of a Neutron external network
    default: ext-floating1

resources:
  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: { get_resource: wait_handle }
      timeout: 600

  wait_handle:
    type: OS::Heat::WaitConditionHandle



  # security group
  MariaDB_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: "MariaDB_security_group"
      description: >
        Allows 3306
      rules:
         - { direction: ingress, protocol: tcp, port_range_min: 3306, port_range_max: 3306 }

  # network resources
  MariaDB_network:
    type: OS::Neutron::Net
    properties:
      name: { get_param: network }
      value_specs:
        mtu: 1500

  MariaDB_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: 'MariaDB-subnet'
      network_id: { get_resource: MariaDB_network }
      cidr: "10.11.3.0/24"
      dns_nameservers:
        - "84.16.67.69"
        - "84.16.67.70"
      ip_version: 4

  MariaDB_router:
    type: OS::Neutron::Router
    properties:
      name:  'MariaDB-router'
      external_gateway_info: { network: ext-floating1 }

  MariaDB_router_subnet_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: MariaDB_router }
      subnet: { get_resource: MariaDB_subnet }

  MariaDB_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: MariaDB_network }
      security_groups: [ { get_resource: MariaDB_security_group } ]
      fixed_ips:
        - subnet_id: { get_resource: MariaDB_subnet }

  MariaDB_floating:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: floating_network_id }
      port_id: { get_resource: MariaDB_port }
  
  database_root_password:
    type: OS::Heat::RandomString

  # instance
  server:
    type: OS::Nova::Server
    depends_on: [ MariaDB_router]
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      networks:
        - port: { get_resource: MariaDB_port }
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v
            apt update && apt upgrade -y
            apt install -y mariadb-server
            systemctl enable --now mariadb
            sed -i s/127.0.0.1/0.0.0.0/ /etc/mysql/mariadb.conf.d/50-server.cnf
            systemctl restart mariadb
            mysqladmin -u root password $db_rootpassword
            cat << EOF | mysql -u root --password=$db_rootpassword
            EXIT
            EOF
            wc_notify --data-binary '{"status": "SUCCESS"}'

          params:
            $db_rootpassword: {get_attr: [database_root_password, value]}
            wc_notify: { get_attr: ['wait_handle', 'curl_cli'] }


outputs:
  server_IP:
    value: 
      str_replace:
        template: IP:3306
        params:
          IP: { get_attr: [MariaDB_floating, floating_ip_address] }
    description: "IP"
  Root_password:
    value: 
      str_replace:
        template: PASSWORD
        params:
          PASSWORD: { get_attr: [database_root_password, value] }
    description: "Root Password"